export const formFicheB12B24 = {
  tenantId: "ps19",
  listName: "appForms",
  code: "formFicheB12B24",
  description: "Form-305-B12-B24",

  opt1: [
    {
      id: "splelementB12",
      fieldName: "Type: SPL 165/10 éléments",
      fieldType: "label",
    },
    {
      id: "technicianB12",
      fieldName: "Technicien",
      fieldType: "text",
      default: "#VAR_UNAME#",
      enabled: false,
    },
    {
      id: "datetimeB12",
      fieldName: "Date / Time",
      fieldType: "text",
      default: "#VAR_NOW#",
      enabled: false,
    },
    {
      id: "vacchargeB12",
      fieldName: "V AC chargeur",
      fieldType: "text",
    },
    {
      id: "dateinstallationB12",
      fieldName: "Date installation:",
      fieldType: "date",
    },
    {
      id: "idccchargeB12",
      fieldName: "I DC Chargeur",
      fieldType: "text",
    },
    {
      id: "vdcbatterieB12",
      fieldName: "V DC batterie",
      fieldType: "label",
    },
    {
      id: "avecchargeB12",
      fieldName: "Avec chargeur",
      fieldType: "text",
    },
    {
      id: "sanschargeB12",
      fieldName: "Sans chargeur",
      fieldType: "text",
    },
    {
      id: "b12B12",
      fieldName: "B 12",
      fieldType: "label",
    },
    {
      id: "tensionperelementB12",
      fieldName: "Tension per élément (Sans chargeur)",
      fieldType: "label",
    },
    {
      id: "tension1B12",
      fieldName: "1",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension2B12",
      fieldName: "2",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension3B12",
      fieldName: "3",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension4B12",
      fieldName: "4",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension5B12",
      fieldName: "5",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension6B12",
      fieldName: "6",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension7B12",
      fieldName: "7",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension8B12",
      fieldName: "8",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension9B12",
      fieldName: "9",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension10B12",
      fieldName: "10",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "commentsB12",
      fieldName: "Commentaires (ajout de l'eau distillée, etc.)",
      fieldType: "text",
    },
    {
      id: "div",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "splelement",
      fieldName: "Type: SPL 340/20 éléments",
      fieldType: "label",
    },
    {
      id: "vaccharge",
      fieldName: "V AC chargeur",
      fieldType: "text",
    },
    {
      id: "dateinstallation",
      fieldName: "Date installation:",
      fieldType: "date",
    },
    {
      id: "idcccharge",
      fieldName: "I DC Chargeur",
      fieldType: "text",
    },
    {
      id: "vdcbatterie",
      fieldName: "V DC batterie",
      fieldType: "label",
    },
    {
      id: "aveccharge",
      fieldName: "Avec chargeur",
      fieldType: "text",
    },
    {
      id: "sanscharge",
      fieldName: "Sans chargeur",
      fieldType: "text",
    },
    {
      id: "b24",
      fieldName: "B 24",
      fieldType: "label",
    },
    {
      id: "tensionperelement",
      fieldName: "Tension per élément (Sans chargeur)",
      fieldType: "label",
    },
    {
      id: "tension1",
      fieldName: "1",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension2",
      fieldName: "2",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension3",
      fieldName: "3",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension4",
      fieldName: "4",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension5",
      fieldName: "5",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension6",
      fieldName: "6",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension7",
      fieldName: "7",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension8",
      fieldName: "8",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension9",
      fieldName: "9",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension10",
      fieldName: "10",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension11",
      fieldName: "11",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension12",
      fieldName: "12",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension13",
      fieldName: "13",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension14",
      fieldName: "14",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension15",
      fieldName: "15",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension16",
      fieldName: "16",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension17",
      fieldName: "17",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension18",
      fieldName: "18",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension19",
      fieldName: "19",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "tension20",
      fieldName: "20",
      fieldType: "number",
      numberDecimal: true,
    },
    {
      id: "comments",
      fieldName: "Commentaires (ajout de l'eau distillée, etc.)",
      fieldType: "text",
    },
    {
      id: "inspected",
      fieldName: "Vous avez terminé l'inspection requise?",
      fieldType: "label",
    },
    {
      id: "yes",
      fieldName: "Oui",
      fieldType: "checkbox",
      tag: "completionCheck",
    },
  ],
  opt2: {
    config: [],
    allowedInstruction: ["GI305.pdf"],
  },
};
