export const assetTypesForIssues = [
  "track",
  "Main Track 1",
  "Main Track 2",
  "CWR Jointed Track",
  "RAR Track",
  "Switch",
  "Switch LH",
  "Switch RH",
  "Yard Track",
  "Yard Track 1",
  "Yard Track 2",
  "Yard Track 3",
  "Side Track",
  "Double Diamond Crossing",
  "Diamond Crossing",
  "Spur",
  "Turnout",
  "Turnout 1",
  "Turnout 2",
  "Turnout 3",
  "Turnout 4",
  "Storage Track",
  "Storage Track 1",
  "Storage Track 2",
  "Customer Track",
  "Customer Switch LH",
  "Customer Switch RH",
  "Customer Switch",
  "Customer Yard Track",
];

export const assetTypeTracks = [
  "track",
  "Main Track 1",
  "Main Track 2",
  "RAR Track",
  "Side Track",
  "Spur",
  "Storage Track 1",
  "Storage Track 2",
  "Storage Track",
  "Customer Track",
];

export const yardTypeATypeTracks = ["RAR Track", "Yard Track", "Yard Track 1", "Yard Track 2", "Yard Track 3", "Customer Yard Track"];
