let Track = require("./../api/track/track.model");
import { guid } from "./UUID";
export function populateSeedDemoDataTracksAssets() {
	baltimoreDiv.forEach(asset => {
		let newAsset = {
			start: asset.start,
			end: asset.end,
			length: asset.length,
			assetType: asset.assetType,
			pastIssue: asset.pastIssue,
			lastInspection: asset.lastInspection,
			nextInspection: asset.nextInspection,
			createdAt: "2018-12-08T21:17:31.482Z",
			updatedAt: "2018-12-08T21:17:31.482Z",
			unitId: asset.unitId,
			id: guid()
		};

		Track.findOne({
			subdivision: asset.subdivision,
			trackId: asset.trackId
		}).exec(function(err, track) {
			if (track) {
				track.units.push(newAsset);
				track.save();
			}
		});
	});
	albanyDiv.forEach(asset => {
		let newAsset = {
			start: asset.start,
			end: asset.end,
			length: asset.length,
			assetType: asset.assetType,
			pastIssue: asset.pastIssue,
			lastInspection: asset.lastInspection,
			nextInspection: asset.nextInspection,
			createdAt: "2018-12-08T21:17:31.482Z",
			updatedAt: "2018-12-08T21:17:31.482Z",
			unitId: asset.unitId,
			id: guid()
		};

		Track.findOne({
			subdivision: asset.subdivision,
			trackId: asset.trackId
		}).exec(function(err, track) {
			if (track) {
				track.units.push(newAsset);
				track.save();
			}
		});
	});

	cumberland.forEach(asset => {
		let newAsset = {
			start: asset.start,
			end: asset.end,
			length: asset.length,
			assetType: asset.assetType,
			pastIssue: asset.pastIssue,
			lastInspection: asset.lastInspection,
			nextInspection: asset.nextInspection,
			createdAt: "2018-12-08T21:17:31.482Z",
			updatedAt: "2018-12-08T21:17:31.482Z",
			unitId: asset.unitId,
			id: guid()
		};

		Track.findOne({
			subdivision: asset.subdivision,
			trackId: asset.trackId
		}).exec(function(err, track) {
			if (track) {
				track.units.push(newAsset);
				track.save();
			}
		});
	});
}

let baltimoreDiv = [
	// {
	// 	start: "101",
	// 	end: "101.1",
	// 	length: "0.1",
	// 	assetType: "Ties",
	// 	pastIssue: "worn rail ",
	// 	lastInspection: "Sep. 2, 2017",
	// 	nextInspection: "Apr. 11, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 1",         unitId: "Asset-0"
	// },
	// {
	// 	start: "101.2",
	// 	end: "101.3",
	// 	length: "0.1",
	// 	assetType: "Rail",
	// 	pastIssue: "cracked rail",
	// 	lastInspection: "Apr. 2, 2017",
	// 	nextInspection: "Oct. 5, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 1",         unitId: "Asset-0"
	// },
	// {
	// 	start: "101.4",
	// 	end: "101.5",
	// 	length: "0.1",
	// 	assetType: "Rail Clips",
	// 	pastIssue: "rotting ties",
	// 	lastInspection: "Jul. 19, 2017",
	// 	nextInspection: "Jan. 31, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 1",         unitId: "Asset-0"
	// },
	// {
	// 	start: "101.6",
	// 	end: "101.7",
	// 	length: "0.1",
	// 	assetType: "spikes ",
	// 	pastIssue: "bouncing rail",
	// 	lastInspection: "Sep. 21, 2017",
	// 	nextInspection: "Aug. 17, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 1",         unitId: "Asset-0"
	// },
	// {
	// 	start: "101.8",
	// 	end: "101.9",
	// 	length: "0.1",
	// 	assetType: "Manual Switch",
	// 	pastIssue: "missing clips",
	// 	lastInspection: "42858",
	// 	nextInspection: "Mar. 3, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 1",         unitId: "Asset-0"
	// },
	// {
	// 	start: "102",
	// 	end: "102.1",
	// 	length: "0.1",
	// 	assetType: "Powered Switch",
	// 	pastIssue: "chipped rail",
	// 	lastInspection: "Aug. 11, 2017",
	// 	nextInspection: "Jun. 12, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 2",         unitId: "Asset-0"
	// },
	// {
	// 	start: "102.2",
	// 	end: "102.3",
	// 	length: "0.1",
	// 	assetType: "Turnout",
	// 	pastIssue: "Draininge ",
	// 	lastInspection: "Apr. 19, 2017",
	// 	nextInspection: "Jun. 2, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 2",         unitId: "Asset-0"
	// },
	// {
	// 	start: "102.4",
	// 	end: "102.5",
	// 	length: "0.1",
	// 	assetType: "Connecting Rod",
	// 	pastIssue: "Vegetation",
	// 	lastInspection: "Nov. 10, 2017",
	// 	nextInspection: "Dec. 15, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 2",         unitId: "Asset-0"
	// },
	// {
	// 	start: "102.6",
	// 	end: "102.7",
	// 	length: "0.1",
	// 	assetType: "Frogs",
	// 	pastIssue: "Gapped Switch point",
	// 	lastInspection: "Mar. 16, 2017",
	// 	nextInspection: "Jul. 15, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 2",         unitId: "Asset-0"
	// },
	// {
	// 	start: "102.8",
	// 	end: "102.9",
	// 	length: "0.1",
	// 	assetType: "Diamonds",
	// 	pastIssue: "loose clips",
	// 	lastInspection: "Feb. 11, 2017",
	// 	nextInspection: "Jan. 5, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 2",         unitId: "Asset-0"
	// },
	// {
	// 	start: "103",
	// 	end: "103.1",
	// 	length: "0.1",
	// 	assetType: "Switch points",
	// 	pastIssue: "worn rail ",
	// 	lastInspection: "Apr. 6, 2017",
	// 	nextInspection: "Mar. 26, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 3",         unitId: "Asset-0"
	// },
	// {
	// 	start: "103.2",
	// 	end: "103.3",
	// 	length: "0.1",
	// 	assetType: "Ties",
	// 	pastIssue: "cracked rail",
	// 	lastInspection: "Dec. 8, 2017",
	// 	nextInspection: "Sep. 13, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 3",         unitId: "Asset-0"
	// },
	// {
	// 	start: "103.4",
	// 	end: "103.5",
	// 	length: "0.1",
	// 	assetType: "Rail",
	// 	pastIssue: "rotting ties",
	// 	lastInspection: "Jan. 6, 2017",
	// 	nextInspection: "Aug. 15, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 3",         unitId: "Asset-0"
	// },
	// {
	// 	start: "103.6",
	// 	end: "103.7",
	// 	length: "0.1",
	// 	assetType: "Rail Clips",
	// 	pastIssue: "bouncing rail",
	// 	lastInspection: "Sep. 5, 2017",
	// 	nextInspection: "Jun. 2, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 3",         unitId: "Asset-0"
	// },
	// {
	// 	start: "103.8",
	// 	end: "103.9",
	// 	length: "0.1",
	// 	assetType: "spikes ",
	// 	pastIssue: "missing clips",
	// 	lastInspection: "Aug. 20, 2017",
	// 	nextInspection: "Feb. 4, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 3",         unitId: "Asset-0"
	// },
	// {
	// 	start: "104",
	// 	end: "104.1",
	// 	length: "0.1",
	// 	assetType: "Manual Switch",
	// 	pastIssue: "chipped rail",
	// 	lastInspection: "Aug. 23, 2017",
	// 	nextInspection: "Apr. 5, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 4",         unitId: "Asset-0"
	// },
	// {
	// 	start: "104.2",
	// 	end: "104.3",
	// 	length: "0.1",
	// 	assetType: "Powered Switch",
	// 	pastIssue: "Draininge ",
	// 	lastInspection: "Mar. 1, 2017",
	// 	nextInspection: "Nov. 15, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 4",         unitId: "Asset-0"
	// },
	// {
	// 	start: "104.4",
	// 	end: "104.5",
	// 	length: "0.1",
	// 	assetType: "Turnout",
	// 	pastIssue: "Vegetation",
	// 	lastInspection: "Nov. 27, 2017",
	// 	nextInspection: "Jul. 12, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 4",         unitId: "Asset-0"
	// },
	// {
	// 	start: "104.6",
	// 	end: "104.7",
	// 	length: "0.1",
	// 	assetType: "Connecting Rod",
	// 	pastIssue: "Gapped Switch point",
	// 	lastInspection: "Jul. 29, 2017",
	// 	nextInspection: "Oct. 12, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 4",         unitId: "Asset-0"
	// },
	// {
	// 	start: "104.8",
	// 	end: "104.9",
	// 	length: "0.1",
	// 	assetType: "Frogs",
	// 	pastIssue: "loose clips",
	// 	lastInspection: "Apr. 19, 2017",
	// 	nextInspection: "Oct. 25, 2018",
	// 	subdivision: "Baltimore Subdivision",
	// 	trackId: "Segment 4",         unitId: "Asset-0"
	// },
	{
		start: "105",
		end: "105.1",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "worn rail ",
		lastInspection: "Nov. 9, 2017",
		nextInspection: "Jan. 18, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-01"
	},
	{
		start: "105.2",
		end: "105.3",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "cracked rail",
		lastInspection: "Dec. 30, 2017",
		nextInspection: "Feb. 8, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-02"
	},
	{
		start: "105.4",
		end: "105.5",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "rotting ties",
		lastInspection: "Nov. 13, 2017",
		nextInspection: "Jun. 14, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-03"
	},
	{
		start: "105.6",
		end: "105.7",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "bouncing rail",
		lastInspection: "Jan. 24, 2017",
		nextInspection: "Dec. 5, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-04"
	},
	{
		start: "105.8",
		end: "105.9",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "missing clips",
		lastInspection: "Jul. 23, 2017",
		nextInspection: "Jun. 2, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-05"
	},
	{
		start: "106",
		end: "106.1",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "chipped rail",
		lastInspection: "Mar. 27, 2017",
		nextInspection: "Sep. 22, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-01"
	},
	{
		start: "106.2",
		end: "106.3",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "Draininge ",
		lastInspection: "42868",
		nextInspection: "Nov. 2, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-02"
	},
	{
		start: "106.4",
		end: "106.5",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "Vegetation",
		lastInspection: "Jan. 8, 2017",
		nextInspection: "Feb. 26, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-03"
	},
	{
		start: "106.6",
		end: "106.7",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "Gapped Switch point",
		lastInspection: "Apr. 23, 2017",
		nextInspection: "Jun. 4, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-04"
	},
	{
		start: "106.8",
		end: "106.9",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "worn rail ",
		lastInspection: "Jan. 25, 2017",
		nextInspection: "Apr. 16, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-05"
	},
	{
		start: "107",
		end: "107.1",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "cracked rail",
		lastInspection: "Nov. 2, 2017",
		nextInspection: "Sep. 17, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-01"
	},
	{
		start: "107.2",
		end: "107.3",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "rotting ties",
		lastInspection: "42873",
		nextInspection: "Jul. 29, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-02"
	},
	{
		start: "107.4",
		end: "107.5",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "bouncing rail",
		lastInspection: "Dec. 30, 2017",
		nextInspection: "Apr. 9, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-03"
	},
	{
		start: "107.6",
		end: "107.7",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "missing clips",
		lastInspection: "Dec. 9, 2017",
		nextInspection: "Apr. 3, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-04"
	},
	{
		start: "107.8",
		end: "107.9",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "chipped rail",
		lastInspection: "Mar. 29, 2017",
		nextInspection: "Jan. 28, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-05"
	},
	{
		start: "108",
		end: "108.1",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Draininge ",
		lastInspection: "Aug. 14, 2017",
		nextInspection: "Jan. 22, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-01"
	},
	{
		start: "108.2",
		end: "108.3",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "Vegetation",
		lastInspection: "Jan. 9, 2017",
		nextInspection: "Jul. 29, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-02"
	},
	{
		start: "108.4",
		end: "108.5",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "Gapped Switch point",
		lastInspection: "Feb. 21, 2017",
		nextInspection: "Oct. 16, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-03"
	},
	{
		start: "108.6",
		end: "108.7",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "loose clips",
		lastInspection: "Oct. 15, 2017",
		nextInspection: "Feb. 5, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-04"
	},
	{
		start: "108.8",
		end: "108.9",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "worn rail ",
		lastInspection: "Jun. 10, 2017",
		nextInspection: "Jun. 8, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-05"
	},
	{
		start: "109",
		end: "109.1",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "cracked rail",
		lastInspection: "Feb. 28, 2017",
		nextInspection: "Apr. 13, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-01"
	},
	{
		start: "109.2",
		end: "109.3",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "rotting ties",
		lastInspection: "Aug. 1, 2017",
		nextInspection: "Sep. 27, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-02"
	},
	{
		start: "109.4",
		end: "109.5",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "bouncing rail",
		lastInspection: "Mar. 28, 2017",
		nextInspection: "Mar. 9, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-03"
	},
	{
		start: "109.6",
		end: "109.7",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "missing clips",
		lastInspection: "Jun. 26, 2017",
		nextInspection: "July. 04,2017",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-04"
	},
	{
		start: "109.8",
		end: "109.9",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "chipped rail",
		lastInspection: "Dec. 19, 2017",
		nextInspection: "Apr. 21, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-05"
	},
	{
		start: "110",
		end: "110.1",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "Draininge ",
		lastInspection: "Apr. 10, 2017",
		nextInspection: "Apr.17,2017",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-01"
	},
	{
		start: "110.2",
		end: "110.3",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Vegetation",
		lastInspection: "Nov. 15, 2017",
		nextInspection: "Oct. 8, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-02"
	},
	{
		start: "110.4",
		end: "110.5",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "Gapped Switch point",
		lastInspection: "Dec. 29, 2017",
		nextInspection: "Jan.052018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-03"
	},
	{
		start: "110.6",
		end: "110.7",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "loose clips",
		lastInspection: "Dec. 11, 2017",
		nextInspection: "Feb. 6, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-04"
	},
	{
		start: "110.8",
		end: "110.9",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "worn rail ",
		lastInspection: "Jan. 17, 2017",
		nextInspection: "Dec. 17, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-05"
	},
	{
		start: "111",
		end: "111.1",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "cracked rail",
		lastInspection: "Aug. 28, 2017",
		nextInspection: "Nov. 3, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-01"
	},
	{
		start: "111.2",
		end: "111.3",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "rotting ties",
		lastInspection: "Apr. 13, 2017",
		nextInspection: "Apr. 14, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-02"
	},
	{
		start: "111.4",
		end: "111.5",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "bouncing rail",
		lastInspection: "42857",
		nextInspection: "Mar. 31, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-03"
	},
	{
		start: "111.6",
		end: "111.7",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "missing clips",
		lastInspection: "Apr. 22, 2017",
		nextInspection: "Dec. 21, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-04"
	},
	{
		start: "111.8",
		end: "111.9",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "chipped rail",
		lastInspection: "Feb. 20, 2017",
		nextInspection: "Feb. 5, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-05"
	},
	{
		start: "112",
		end: "112.1",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "Draininge ",
		lastInspection: "Jul. 26, 2017",
		nextInspection: "July.04,2017",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-01"
	},
	{
		start: "112.2",
		end: "112.3",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "Vegetation",
		lastInspection: "Sep. 23, 2017",
		nextInspection: "Feb. 7, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-02"
	},
	{
		start: "112.4",
		end: "112.5",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Gapped Switch point",
		lastInspection: "Jul. 10, 2017",
		nextInspection: "Nov. 11, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-03"
	},
	{
		start: "112.6",
		end: "112.7",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "worn rail ",
		lastInspection: "Jan. 26, 2017",
		nextInspection: "Feb. 04, 2017",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-04"
	},
	{
		start: "112.8",
		end: "112.9",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "cracked rail",
		lastInspection: "Mar. 9, 2017",
		nextInspection: "Mar.06,2017",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-05"
	},
	{
		start: "113",
		end: "113.1",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "rotting ties",
		lastInspection: "Mar. 23, 2017",
		nextInspection: "Jul. 29, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-01"
	},
	{
		start: "113.2",
		end: "113.3",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "bouncing rail",
		lastInspection: "Jun. 23, 2017",
		nextInspection: "Aug. 27, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-02"
	},
	{
		start: "113.4",
		end: "113.5",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "missing clips",
		lastInspection: "Oct. 26, 2017",
		nextInspection: "Mar. 3, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-03"
	},
	{
		start: "113.6",
		end: "113.7",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "chipped rail",
		lastInspection: "Feb. 27, 2017",
		nextInspection: "Mar.17,2017",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-04"
	},
	{
		start: "113.8",
		end: "113.9",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "Draininge ",
		lastInspection: "42864",
		nextInspection: "Mar. 21, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-05"
	},
	{
		start: "114",
		end: "114.1",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "Vegetation",
		lastInspection: "Oct. 23, 2017",
		nextInspection: "Sep. 27, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-01"
	},
	{
		start: "114.2",
		end: "114.3",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "Gapped Switch point",
		lastInspection: "Jan. 11, 2017",
		nextInspection: "Feb. 16, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-02"
	},
	{
		start: "114.4",
		end: "114.5",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "loose clips",
		lastInspection: "Jun. 20, 2017",
		nextInspection: "Apr. 28, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-03"
	},
	{
		start: "114.6",
		end: "114.7",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "worn rail ",
		lastInspection: "Apr. 29, 2017",
		nextInspection: "Sep. 3, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-04"
	},
	{
		start: "114.8",
		end: "114.9",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "cracked rail",
		lastInspection: "Oct. 20, 2017",
		nextInspection: "Jan. 2, 2018",
		subdivision: "Baltimore Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-05"
	}
];

// ALBANY LAND OBJECT

let albanyDiv = [
	{
		start: "101",
		end: "101.1",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "rotting ties",
		lastInspection: "Jun. 30, 2017",
		nextInspection: "Feb. 10, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-01"
	},
	{
		start: "101.2",
		end: "101.3",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "bouncing rail",
		lastInspection: "Apr. 4, 2017",
		nextInspection: "Sep. 24, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-02"
	},
	{
		start: "101.4",
		end: "101.5",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "missing clips",
		lastInspection: "42879",
		nextInspection: "Aug. 18, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-03"
	},
	{
		start: "101.6",
		end: "101.7",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "chipped rail",
		lastInspection: "Mar. 22, 2017",
		nextInspection: "Dec. 20, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-04"
	},
	{
		start: "101.8",
		end: "101.9",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "Draininge ",
		lastInspection: "Feb. 18, 2017",
		nextInspection: "Nov. 30, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-05"
	},
	{
		start: "102",
		end: "102.1",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "Vegetation",
		lastInspection: "Feb. 13, 2017",
		nextInspection: "Jun. 24, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-01"
	},
	{
		start: "102.2",
		end: "102.3",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "Gapped Switch point",
		lastInspection: "Oct. 7, 2017",
		nextInspection: "Mar. 21, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-02"
	},
	{
		start: "102.4",
		end: "102.5",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "loose clips",
		lastInspection: "Sep. 30, 2017",
		nextInspection: "Dec. 29, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-03"
	},
	{
		start: "102.6",
		end: "102.7",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "worn rail ",
		lastInspection: "Feb. 24, 2017",
		nextInspection: "Jan. 7, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-04"
	},
	{
		start: "102.8",
		end: "102.9",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "cracked rail",
		lastInspection: "Dec. 11, 2017",
		nextInspection: "Aug. 8, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-05"
	},
	{
		start: "103",
		end: "103.1",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "rotting ties",
		lastInspection: "Jul. 6, 2017",
		nextInspection: "Mar. 19, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-01"
	},
	{
		start: "103.2",
		end: "103.3",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "bouncing rail",
		lastInspection: "Mar. 5, 2017",
		nextInspection: "Feb. 16, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-02"
	},
	{
		start: "103.4",
		end: "103.5",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "missing clips",
		lastInspection: "Dec. 12, 2017",
		nextInspection: "Oct. 24, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-03"
	},
	{
		start: "103.6",
		end: "103.7",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "chipped rail",
		lastInspection: "Oct. 23, 2017",
		nextInspection: "Mar. 4, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-04"
	},
	{
		start: "103.8",
		end: "103.9",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "Draininge ",
		lastInspection: "Jul. 26, 2017",
		nextInspection: "Feb. 15, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-05"
	},
	{
		start: "104",
		end: "104.1",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "Vegetation",
		lastInspection: "Jul. 24, 2017",
		nextInspection: "Feb. 8, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-01"
	},
	{
		start: "104.2",
		end: "104.3",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "Gapped Switch point",
		lastInspection: "Apr. 8, 2017",
		nextInspection: "Feb. 11, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-02"
	},
	{
		start: "104.4",
		end: "104.5",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "worn rail ",
		lastInspection: "Jan. 8, 2017",
		nextInspection: "Apr. 16, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-03"
	},
	{
		start: "104.6",
		end: "104.7",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "cracked rail",
		lastInspection: "Jul. 7, 2017",
		nextInspection: "Jun. 29, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-04"
	},
	{
		start: "104.8",
		end: "104.9",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "rotting ties",
		lastInspection: "Aug. 5, 2017",
		nextInspection: "Feb. 18, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-05"
	},
	{
		start: "105",
		end: "105.1",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "bouncing rail",
		lastInspection: "Sep. 27, 2017",
		nextInspection: "Oct.05,2017",
		subdivision: "Albany Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-01"
	},
	{
		start: "105.2",
		end: "105.3",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "missing clips",
		lastInspection: "42881",
		nextInspection: "June. 03,2017",
		subdivision: "Albany Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-02"
	},
	{
		start: "105.4",
		end: "105.5",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "chipped rail",
		lastInspection: "Aug. 9, 2017",
		nextInspection: "Jan. 10, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-03"
	},
	{
		start: "105.6",
		end: "105.7",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Draininge ",
		lastInspection: "Dec. 14, 2017",
		nextInspection: "Nov. 3, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-04"
	},
	{
		start: "105.8",
		end: "105.9",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "Vegetation",
		lastInspection: "Jun. 18, 2017",
		nextInspection: "Dec. 17, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-05"
	},
	{
		start: "106",
		end: "106.1",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "Gapped Switch point",
		lastInspection: "Jan. 14, 2017",
		nextInspection: "Apr. 6, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-01"
	},
	{
		start: "106.2",
		end: "106.3",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "loose clips",
		lastInspection: "Aug. 28, 2017",
		nextInspection: "Dec. 26, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-02"
	},
	{
		start: "106.4",
		end: "106.5",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "worn rail ",
		lastInspection: "Dec. 17, 2017",
		nextInspection: "Jun. 16, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-03"
	},
	{
		start: "106.6",
		end: "106.7",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "cracked rail",
		lastInspection: "Jul. 31, 2017",
		nextInspection: "Apr. 21, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-04"
	},
	{
		start: "106.8",
		end: "106.9",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "rotting ties",
		lastInspection: "Dec. 11, 2017",
		nextInspection: "Apr. 17, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-05"
	},
	{
		start: "107",
		end: "107.1",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "bouncing rail",
		lastInspection: "Jul. 27, 2017",
		nextInspection: "Jan. 12, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-01"
	},
	{
		start: "107.2",
		end: "107.3",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "missing clips",
		lastInspection: "Dec. 2, 2017",
		nextInspection: "Mar. 12, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-02"
	},
	{
		start: "107.4",
		end: "107.5",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "chipped rail",
		lastInspection: "Nov. 19, 2017",
		nextInspection: "Aug. 24, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-03"
	},
	{
		start: "107.6",
		end: "107.7",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "Draininge ",
		lastInspection: "Jun. 24, 2017",
		nextInspection: "Nov. 27, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-04"
	},
	{
		start: "107.8",
		end: "107.9",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Vegetation",
		lastInspection: "Jul. 4, 2017",
		nextInspection: "Apr. 3, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-05"
	},
	{
		start: "108",
		end: "108.1",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Gapped Switch point",
		lastInspection: "Mar. 12, 2017",
		nextInspection: "Jun. 30, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-01"
	},
	{
		start: "108.2",
		end: "108.3",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "loose clips",
		lastInspection: "Oct. 8, 2017",
		nextInspection: "Mar. 15, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-02"
	},
	{
		start: "108.4",
		end: "108.5",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "worn rail ",
		lastInspection: "Feb. 21, 2017",
		nextInspection: "Jul. 6, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-03"
	},
	{
		start: "108.6",
		end: "108.7",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "cracked rail",
		lastInspection: "Jan. 5, 2017",
		nextInspection: "Sep. 5, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-04"
	},
	{
		start: "108.8",
		end: "108.9",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "rotting ties",
		lastInspection: "42868",
		nextInspection: "Dec. 8, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-05"
	},
	{
		start: "109",
		end: "109.1",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "bouncing rail",
		lastInspection: "Jun. 18, 2017",
		nextInspection: "Oct. 20, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-01"
	},
	{
		start: "109.2",
		end: "109.3",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "missing clips",
		lastInspection: "Jul. 8, 2017",
		nextInspection: "Oct. 5, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-02"
	},
	{
		start: "109.4",
		end: "109.5",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "chipped rail",
		lastInspection: "Feb. 14, 2017",
		nextInspection: "Sep. 23, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-03"
	},
	{
		start: "109.6",
		end: "109.7",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "Draininge ",
		lastInspection: "Dec. 2, 2017",
		nextInspection: "Feb. 6, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-04"
	},
	{
		start: "109.8",
		end: "109.9",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "Vegetation",
		lastInspection: "Oct. 22, 2017",
		nextInspection: "Nov. 8, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-05"
	},
	{
		start: "110",
		end: "110.1",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "Gapped Switch point",
		lastInspection: "Oct. 16, 2017",
		nextInspection: "Jan. 30, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-01"
	},
	{
		start: "110.2",
		end: "110.3",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "worn rail ",
		lastInspection: "Jul. 11, 2017",
		nextInspection: "Jul. 3, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-02"
	},
	{
		start: "110.4",
		end: "110.5",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "cracked rail",
		lastInspection: "Aug. 12, 2017",
		nextInspection: "Nov. 29, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-03"
	},
	{
		start: "110.6",
		end: "110.7",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "rotting ties",
		lastInspection: "Dec. 1, 2017",
		nextInspection: "Jun. 11, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-04"
	},
	{
		start: "110.8",
		end: "110.9",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "bouncing rail",
		lastInspection: "42871",
		nextInspection: "May.25,2017",
		subdivision: "Albany Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-05"
	},
	{
		start: "111",
		end: "111.1",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "missing clips",
		lastInspection: "Mar. 3, 2017",
		nextInspection: "Jul. 19, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-01"
	},
	{
		start: "111.2",
		end: "111.3",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "chipped rail",
		lastInspection: "Jul. 29, 2017",
		nextInspection: "Feb. 13, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-02"
	},
	{
		start: "111.4",
		end: "111.5",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "Draininge ",
		lastInspection: "Sep. 24, 2017",
		nextInspection: "Jan. 25, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-03"
	},
	{
		start: "111.6",
		end: "111.7",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "Vegetation",
		lastInspection: "Oct. 12, 2017",
		nextInspection: "Aug. 7, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-04"
	},
	{
		start: "111.8",
		end: "111.9",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "Gapped Switch point",
		lastInspection: "Feb. 5, 2017",
		nextInspection: "Nov. 27, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-05"
	},
	{
		start: "112",
		end: "112.1",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "loose clips",
		lastInspection: "Jan. 22, 2017",
		nextInspection: "Aug. 17, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-01"
	},
	{
		start: "112.2",
		end: "112.3",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "worn rail ",
		lastInspection: "Jul. 26, 2017",
		nextInspection: "Jun. 8, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-02"
	},
	{
		start: "112.4",
		end: "112.5",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "cracked rail",
		lastInspection: "Apr. 5, 2017",
		nextInspection: "Oct. 9, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-03"
	},
	{
		start: "112.6",
		end: "112.7",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "rotting ties",
		lastInspection: "Mar. 7, 2017",
		nextInspection: "Dec. 25, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-04"
	},
	{
		start: "112.8",
		end: "112.9",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "bouncing rail",
		lastInspection: "Jan. 10, 2017",
		nextInspection: "Nov. 20, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-05"
	},
	{
		start: "113",
		end: "113.1",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "missing clips",
		lastInspection: "Mar. 8, 2017",
		nextInspection: "Jan. 13, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-01"
	},
	{
		start: "113.2",
		end: "113.3",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "chipped rail",
		lastInspection: "Dec. 22, 2017",
		nextInspection: "Apr. 4, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-02"
	},
	{
		start: "113.4",
		end: "113.5",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "Draininge ",
		lastInspection: "Feb. 7, 2017",
		nextInspection: "Jun. 8, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-03"
	},
	{
		start: "113.6",
		end: "113.7",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "Vegetation",
		lastInspection: "Jan. 8, 2017",
		nextInspection: "Jul. 16, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-04"
	},
	{
		start: "113.8",
		end: "113.9",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "Gapped Switch point",
		lastInspection: "Sep. 15, 2017",
		nextInspection: "Oct. 23, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-05"
	},
	{
		start: "114",
		end: "114.1",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "loose clips",
		lastInspection: "Jan. 22, 2017",
		nextInspection: "Mar. 24, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-01"
	},
	{
		start: "114.2",
		end: "114.3",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "worn rail ",
		lastInspection: "Oct. 10, 2017",
		nextInspection: "Oct. 8, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-02"
	},
	{
		start: "114.4",
		end: "114.5",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "cracked rail",
		lastInspection: "Sep. 9, 2017",
		nextInspection: "Jun. 21, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-03"
	},
	{
		start: "114.6",
		end: "114.7",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "rotting ties",
		lastInspection: "Jul. 31, 2017",
		nextInspection: "Sep. 2, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-04"
	},
	{
		start: "114.8",
		end: "114.9",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "bouncing rail",
		lastInspection: "Jan. 12, 2017",
		nextInspection: "Oct. 31, 2018",
		subdivision: "Albany Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-05"
	}
];

// CUMBER LAND OBJECT
let cumberland = [
	{
		start: "101",
		end: "101.1",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "missing clips",
		lastInspection: "Apr. 17, 2017",
		nextInspection: "Jun. 22, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-01"
	},
	{
		start: "101.2",
		end: "101.3",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "chipped rail",
		lastInspection: "Apr. 12, 2017",
		nextInspection: "Jun. 27, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-02"
	},
	{
		start: "101.4",
		end: "101.5",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "Draininge ",
		lastInspection: "Dec. 13, 2017",
		nextInspection: "Jan. 4, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-03"
	},
	{
		start: "101.6",
		end: "101.7",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "Vegetation",
		lastInspection: "Jun. 4, 2017",
		nextInspection: "Jun. 7, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-04"
	},
	{
		start: "101.8",
		end: "101.9",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "Gapped Switch point",
		lastInspection: "Jun. 5, 2017",
		nextInspection: "Mar. 15, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 1",
		unitId: "Asset-05"
	},
	{
		start: "102",
		end: "102.1",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "worn rail ",
		lastInspection: "42877",
		nextInspection: "June. 03,2017",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-01"
	},
	{
		start: "102.2",
		end: "102.3",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "cracked rail",
		lastInspection: "Feb. 4, 2017",
		nextInspection: "Sep. 12, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-02"
	},
	{
		start: "102.4",
		end: "102.5",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "rotting ties",
		lastInspection: "Dec. 8, 2017",
		nextInspection: "Dec. 05,2017",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-03"
	},
	{
		start: "102.6",
		end: "102.7",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "bouncing rail",
		lastInspection: "Dec. 9, 2017",
		nextInspection: "Sep. 28, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-04"
	},
	{
		start: "102.8",
		end: "102.9",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "missing clips",
		lastInspection: "Dec. 8, 2017",
		nextInspection: "Feb. 1, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 2",
		unitId: "Asset-05"
	},
	{
		start: "103",
		end: "103.1",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "chipped rail",
		lastInspection: "Jun. 4, 2017",
		nextInspection: "Jun. 17,2017",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-01"
	},
	{
		start: "103.2",
		end: "103.3",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Draininge ",
		lastInspection: "Jun. 17, 2017",
		nextInspection: "Nov. 19, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-02"
	},
	{
		start: "103.4",
		end: "103.5",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "Vegetation",
		lastInspection: "Sep. 11, 2017",
		nextInspection: "Dec. 1, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-03"
	},
	{
		start: "103.6",
		end: "103.7",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "Gapped Switch point",
		lastInspection: "Jan. 28, 2017",
		nextInspection: "Jan. 4, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-04"
	},
	{
		start: "103.8",
		end: "103.9",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "loose clips",
		lastInspection: "Feb. 10, 2017",
		nextInspection: "Apr. 18, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 3",
		unitId: "Asset-05"
	},
	{
		start: "104",
		end: "104.1",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "worn rail ",
		lastInspection: "Apr. 10, 2017",
		nextInspection: "Apr. 17, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-01"
	},
	{
		start: "104.2",
		end: "104.3",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "cracked rail",
		lastInspection: "Mar. 7, 2017",
		nextInspection: "Oct. 28, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-02"
	},
	{
		start: "104.4",
		end: "104.5",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "rotting ties",
		lastInspection: "Nov. 7, 2017",
		nextInspection: "Dec. 30, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-03"
	},
	{
		start: "104.6",
		end: "104.7",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "bouncing rail",
		lastInspection: "Mar. 8, 2017",
		nextInspection: "Dec. 2, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-04"
	},
	{
		start: "104.8",
		end: "104.9",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "missing clips",
		lastInspection: "Oct. 11, 2017",
		nextInspection: "Apr. 13, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 4",
		unitId: "Asset-05"
	},
	{
		start: "105",
		end: "105.1",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "chipped rail",
		lastInspection: "Aug. 18, 2017",
		nextInspection: "Feb. 4, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-01"
	},
	{
		start: "105.2",
		end: "105.3",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "Draininge ",
		lastInspection: "42866",
		nextInspection: "Mar. 12, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-02"
	},
	{
		start: "105.4",
		end: "105.5",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Vegetation",
		lastInspection: "Feb. 21, 2017",
		nextInspection: "Jul. 2, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-03"
	},
	{
		start: "105.6",
		end: "105.7",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Gapped Switch point",
		lastInspection: "Feb. 16, 2017",
		nextInspection: "Dec. 25, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-04"
	},
	{
		start: "105.8",
		end: "105.9",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "loose clips",
		lastInspection: "Nov. 7, 2017",
		nextInspection: "Apr. 20, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 5",
		unitId: "Asset-05"
	},
	{
		start: "106",
		end: "106.1",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "worn rail ",
		lastInspection: "Jul. 18, 2017",
		nextInspection: "Mar. 14, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-01"
	},
	{
		start: "106.2",
		end: "106.3",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "cracked rail",
		lastInspection: "Apr. 30, 2017",
		nextInspection: "Mar. 30, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-02"
	},
	{
		start: "106.4",
		end: "106.5",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "rotting ties",
		lastInspection: "Aug. 12, 2017",
		nextInspection: "Sep. 17, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-03"
	},
	{
		start: "106.6",
		end: "106.7",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "bouncing rail",
		lastInspection: "Jan. 2, 2017",
		nextInspection: "Sep. 28, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-04"
	},
	{
		start: "106.8",
		end: "106.9",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "missing clips",
		lastInspection: "Aug. 7, 2017",
		nextInspection: "Aug. 23, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 6",
		unitId: "Asset-05"
	},
	{
		start: "107",
		end: "107.1",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "chipped rail",
		lastInspection: "Oct. 22, 2017",
		nextInspection: "Aug. 24, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-01"
	},
	{
		start: "107.2",
		end: "107.3",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "Draininge ",
		lastInspection: "Jun. 27, 2017",
		nextInspection: "Feb. 4, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-02"
	},
	{
		start: "107.4",
		end: "107.5",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "Vegetation",
		lastInspection: "Aug. 7, 2017",
		nextInspection: "Jun. 15, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-03"
	},
	{
		start: "107.6",
		end: "107.7",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "Gapped Switch point",
		lastInspection: "Mar. 6, 2017",
		nextInspection: "Mar. 18, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-04"
	},
	{
		start: "107.8",
		end: "107.9",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "worn rail ",
		lastInspection: "Mar. 15, 2017",
		nextInspection: "Aug. 29, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 7",
		unitId: "Asset-05"
	},
	{
		start: "108",
		end: "108.1",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "cracked rail",
		lastInspection: "Jul. 31, 2017",
		nextInspection: "Apr. 21, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-01"
	},
	{
		start: "108.2",
		end: "108.3",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "rotting ties",
		lastInspection: "42871",
		nextInspection: "Mar. 25, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-02"
	},
	{
		start: "108.4",
		end: "108.5",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "bouncing rail",
		lastInspection: "Jun. 25, 2017",
		nextInspection: "Apr. 13, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-03"
	},
	{
		start: "108.6",
		end: "108.7",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "missing clips",
		lastInspection: "Mar. 10, 2017",
		nextInspection: "Mar. 21,2017",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-04"
	},
	{
		start: "108.8",
		end: "108.9",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "chipped rail",
		lastInspection: "Mar. 9, 2017",
		nextInspection: "Apr. 3, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 8",
		unitId: "Asset-05"
	},
	{
		start: "109",
		end: "109.1",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "Draininge ",
		lastInspection: "Nov. 7, 2017",
		nextInspection: "Sep. 30, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-01"
	},
	{
		start: "109.2",
		end: "109.3",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "Vegetation",
		lastInspection: "Dec. 7, 2017",
		nextInspection: "Apr. 18, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-02"
	},
	{
		start: "109.4",
		end: "109.5",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "Gapped Switch point",
		lastInspection: "Sep. 22, 2017",
		nextInspection: "Feb. 12, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-03"
	},
	{
		start: "109.6",
		end: "109.7",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "loose clips",
		lastInspection: "42878",
		nextInspection: "Apr. 20, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-04"
	},
	{
		start: "109.8",
		end: "109.9",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "worn rail ",
		lastInspection: "Jan. 30, 2017",
		nextInspection: "Feb. 24, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 9",
		unitId: "Asset-05"
	},
	{
		start: "110",
		end: "110.1",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "cracked rail",
		lastInspection: "Sep. 10, 2017",
		nextInspection: "Jul. 1, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-01"
	},
	{
		start: "110.2",
		end: "110.3",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "rotting ties",
		lastInspection: "Jun. 22, 2017",
		nextInspection: "Aug. 25, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-02"
	},
	{
		start: "110.4",
		end: "110.5",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "bouncing rail",
		lastInspection: "Jan. 6, 2017",
		nextInspection: "Jan. 26, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-03"
	},
	{
		start: "110.6",
		end: "110.7",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "missing clips",
		lastInspection: "42881",
		nextInspection: "Dec. 5, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-04"
	},
	{
		start: "110.8",
		end: "110.9",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "chipped rail",
		lastInspection: "Nov. 4, 2017",
		nextInspection: "Jan. 19, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 10",
		unitId: "Asset-05"
	},
	{
		start: "111",
		end: "111.1",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "Draininge ",
		lastInspection: "Nov. 23, 2017",
		nextInspection: "Jul. 11, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-01"
	},
	{
		start: "111.2",
		end: "111.3",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "Vegetation",
		lastInspection: "Nov. 21, 2017",
		nextInspection: "Jan. 27, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-02"
	},
	{
		start: "111.4",
		end: "111.5",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "Gapped Switch point",
		lastInspection: "Oct. 28, 2017",
		nextInspection: "Apr. 17, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-03"
	},
	{
		start: "111.6",
		end: "111.7",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "loose clips",
		lastInspection: "Jun. 13, 2017",
		nextInspection: "Mar. 22, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-04"
	},
	{
		start: "111.8",
		end: "111.9",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "worn rail ",
		lastInspection: "Feb. 14, 2017",
		nextInspection: "Aug. 21, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 11",
		unitId: "Asset-05"
	},
	{
		start: "112",
		end: "112.1",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "cracked rail",
		lastInspection: "Apr. 27, 2017",
		nextInspection: "Jul. 8, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-01"
	},
	{
		start: "112.2",
		end: "112.3",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "rotting ties",
		lastInspection: "42872",
		nextInspection: "Sep. 12, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-02"
	},
	{
		start: "112.4",
		end: "112.5",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "bouncing rail",
		lastInspection: "Jun. 1, 2017",
		nextInspection: "Dec. 4, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-03"
	},
	{
		start: "112.6",
		end: "112.7",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "missing clips",
		lastInspection: "Jun. 23, 2017",
		nextInspection: "Jan. 22, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-04"
	},
	{
		start: "112.8",
		end: "112.9",
		length: "0.1",
		assetType: "Rail",
		pastIssue: "chipped rail",
		lastInspection: "Feb. 8, 2017",
		nextInspection: "Nov. 15, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 12",
		unitId: "Asset-05"
	},
	{
		start: "113",
		end: "113.1",
		length: "0.1",
		assetType: "Rail Clips",
		pastIssue: "Draininge ",
		lastInspection: "Dec. 26, 2017",
		nextInspection: "Apr. 19, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-01"
	},
	{
		start: "113.2",
		end: "113.3",
		length: "0.1",
		assetType: "spikes ",
		pastIssue: "Vegetation",
		lastInspection: "Oct. 30, 2017",
		nextInspection: "Dec. 31, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-02"
	},
	{
		start: "113.4",
		end: "113.5",
		length: "0.1",
		assetType: "Manual Switch",
		pastIssue: "Gapped Switch point",
		lastInspection: "Mar. 17, 2017",
		nextInspection: "Oct. 28, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-03"
	},
	{
		start: "113.6",
		end: "113.7",
		length: "0.1",
		assetType: "Powered Switch",
		pastIssue: "worn rail ",
		lastInspection: "Jul. 7, 2017",
		nextInspection: "Sep. 30, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-04"
	},
	{
		start: "113.8",
		end: "113.9",
		length: "0.1",
		assetType: "Turnout",
		pastIssue: "cracked rail",
		lastInspection: "Jan. 18, 2017",
		nextInspection: "Mar. 11, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 13",
		unitId: "Asset-05"
	},
	{
		start: "114",
		end: "114.1",
		length: "0.1",
		assetType: "Connecting Rod",
		pastIssue: "rotting ties",
		lastInspection: "Jan. 9, 2017",
		nextInspection: "Oct. 29, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-01"
	},
	{
		start: "114.2",
		end: "114.3",
		length: "0.1",
		assetType: "Frogs",
		pastIssue: "bouncing rail",
		lastInspection: "Dec. 28, 2017",
		nextInspection: "Nov. 5, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-02"
	},
	{
		start: "114.4",
		end: "114.5",
		length: "0.1",
		assetType: "Diamonds",
		pastIssue: "missing clips",
		lastInspection: "Dec. 12, 2017",
		nextInspection: "Apr. 23, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-03"
	},
	{
		start: "114.6",
		end: "114.7",
		length: "0.1",
		assetType: "Switch points",
		pastIssue: "chipped rail",
		lastInspection: "42882",
		nextInspection: "Nov. 14, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-04"
	},
	{
		start: "114.8",
		end: "114.9",
		length: "0.1",
		assetType: "Ties",
		pastIssue: "Draininge ",
		lastInspection: "Sep. 18, 2017",
		nextInspection: "Nov. 15, 2018",
		subdivision: "Cumberland Subdivision",
		trackId: "Segment 14",
		unitId: "Asset-05"
	}
];
