import { basicColors, retroColors } from "style/basic/basicColors";
export const paginationStyle = {
  myButtonNext: {
    default: {
      backgroundColor: basicColors.fourth,
      display: "block",
      width: "100%",
      height: "100%",
      border: "1px solid ",
      borderColor: basicColors.first,
      borderRadius: "0px 4px 4px 0px",
      padding: "2px 10px",
      fontFamily: "Arial",
      fontsize: "11px",
      letterSpacing: "0.28px",
      color: basicColors.first,
      transition: "all 0.1s ease",
      cursor: "pointer",
      outline: "none",
    },
    retro: {
      backgroundColor: retroColors.fourth,
      display: "block",
      borderRadius: "0px",
      padding: "8px",
      fontFamily: "Arial",
      letterSpacing: "0.28px",
      color: retroColors.second,
      transition: "all 0.1s ease",
      cursor: "pointer",
      outline: "none",
      textTransform: "Capitalize",
      fontSize: "11px !important",
    },
  },

  myButtonPrev: {
    default: {
      backgroundColor: basicColors.fourth,
      display: "block",
      width: "100%",
      height: "100%",
      border: "1px solid ",
      borderColor: basicColors.first,
      borderRadius: "0px 4px 4px 0px",
      padding: "2px 10px",
      fontFamily: "Arial",
      fontsize: "11px",
      letterSpacing: "0.28px",
      color: basicColors.first,
      transition: "all 0.1s ease",
      cursor: "pointer",
      outline: "none",
    },
    retro: {
      backgroundColor: retroColors.fourth,
      display: "block",
      borderRadius: "0px ",
      padding: "8px",
      fontFamily: "Arial",
      fontsize: "11px",
      letterSpacing: "0.28px",
      color: retroColors.second,
      transition: "all 0.1s ease",
      cursor: "pointer",
      outline: "none",
      textTransform: "Capitalize",
      fontSize: "11px !important",
    },
  },
  paginationCustom: {
    default: { float: "right" },
    retro: { float: "right", marginRight: "15px", marginBottom: "20px" },
  },
  customCenter: {
    default: { display: "inline-block" },
    retro: { display: "none" },
  },
  entriesContainer: {
    default: {
      fontFamily: "Arial",
      fontSize: "11px",
      letterSpacing: "0.28px",
      color: "#a7cdb8",
    },
    retro: { display: "none" },
  },
  entriesContainerRetro: {
    default: {
      display: "none",
    },
    retro: {
      backgroundColor: retroColors.fourth,
      display: "inline-block",
      borderRadius: "0px ",
      padding: "8px",
      fontFamily: "Arial",
      fontSize: "10px",
      letterSpacing: "0.28px",
      color: retroColors.second,
      transition: "all 0.1s ease",
      cursor: "pointer",
      outline: "none",
      margin: "0 10px",
      verticalAlign: "top",
    },
  },
};
