export const etrBridgeForm = {
  tenantId: "ps19",
  listName: "appForms",
  code: "etrBridgeForm",
  description: "Bridge Inspection Form",
  opt2: { config: [], allowedInstruction: [], restrictAssetTypes: [], allowedAssetTypes: ["Bridge"] },
  opt1: [
    {
      id: "inspected",
      fieldName: "Inspected",
      fieldType: "checkbox",
      tag: "completionCheck",
    },
    {
      id: "t-loc",
      fieldName: "Location of Defect",
      fieldType: "label",
    },
    {
      id: "div",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "li-bolt",
      fieldName: "Bolt Missing/ Broken",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-bar",
      fieldName: "Broken Joint Bars",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-rail",
      fieldName: "Broken Rail",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-appro",
      fieldName: "Approaches",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-timb",
      fieldName: "Bridge Timbers",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-plat",
      fieldName: "Tie Plates",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-apar",
      fieldName: "Pull Apart",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-anch",
      fieldName: "Rail Anchors",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-rust",
      fieldName: "Rust / Debris",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-gaug",
      fieldName: "Wide Gauge",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-vege",
      fieldName: "Vegetation",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-hook",
      fieldName: "Hook Bolts",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-rivet",
      fieldName: "Rivets or Bolts",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-not",
      fieldName: "Not Listed",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-span",
      fieldName: "Overall Condition of Bridge Including: Bottom Bracings; Bents; Spans & Stiffeners",
      fieldType: "list",
      options: ["-", "Good", "Defect", "Satisfactory"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "li-act",
      fieldName: "Action Taken By Inspector",
      fieldType: "list",
      options: ["-", "Inspector Corrected", "Slow Order", "Out of Service"],
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
    {
      id: "tx-comm",
      fieldName: "Comments",
      fieldType: "text",
    },
    {
      id: "tx-sp",
      fieldName: " ",
      fieldType: "label",
    },
  ],
};
