let express = require("express");
let router = express.Router();

let user_route = require("./../api/user/index");
let alert_route = require("./../api/Alert/index");
let user_group_route = require("./../api/userGroup/index");
let local_route = require("./../auth/local/index");
let attendance_route = require("./../api/attendance/index");
let userHours_route = require("./../api/userHours/index");

let msglist_route = require("./../api/msglist/index");
let list_route = require("./../api/list/index");
let SOD_route = require("./../api/SOD/index");
let applicationLookups_route = require("./../api/ApplicationLookups/index");
let applicationresources_route = require("./../api/ApplicationResources/index");
let permissions_route = require("./../api/permission/index");
let assets_route = require("./../api/assets/index");
let assetTypes_route = require("./../api/assetTypes/index");
let maintenance_route = require("./../api/Maintenance/index");
let run_route = require("./../api/run/index");
let runRange_route = require("./../api/runRange/index");
let gpslog_route = require("./../api/GpsLog/index");
let dashboard_route = require("./../api/dashboard/index");
let workorder_route = require("./../api/workOrder/index");
let notification_route = require("./../api/Notification/index");
let migration_route = require("./../api/migrations/index");
let version_route = require("./../api/version/index");
let asset_test_route = require("./../api/AssetTests/index");
let error_reporting_route = require("./../api/ErrorReporting/index");
let lostnfound_route = require("./../api/Lostnfound/index");
let assetReports =  require("./../timps/api/InspectionReports/index");
let jPlan = require("./../timps/api/journeyPlan/index");
router.use("/login", local_route);
router.use("/users", user_route);
router.use("/userHours", userHours_route);
router.use("/userGroup", user_group_route);
router.use("/attendance", attendance_route);
router.use("/asset", assets_route);
router.use("/runNumber", run_route);
router.use("/runDetail", runRange_route);
router.use("/list", list_route);
router.use("/msglist", msglist_route);
router.use("/SOD", SOD_route);
router.use("/applicationlookups", applicationLookups_route);
router.use("/applicationresources", applicationresources_route);
router.use("/permission", permissions_route);
router.use("/assettype", assetTypes_route);
router.use("/maintenance", maintenance_route);
router.use("/GpsLog", gpslog_route);
router.use("/dashboard", dashboard_route);
router.use("/workorder", workorder_route);
router.use("/notification", notification_route);
router.use("/patch", migration_route);
router.use("/alert", alert_route);
router.use("/version", version_route);
router.use("/assetTest", asset_test_route);
router.use("/errorReporting", error_reporting_route);
router.use("/assetReports", assetReports);
router.use("/journeyPlan",jPlan);
module.exports = router;
