export const batteryCardForm = [
  {
    id: "circ",
    fieldName: "Circuit",
    fieldType: "text",
  },
  {
    id: "d_inst",
    fieldName: "Date installed",
    fieldType: "date",
    enabled: true,
  },
  {
    id: "mode",
    fieldName: "Model",
    fieldType: "text",
  },
  {
    id: "ni",
    fieldName: "Battery Type",
    fieldType: "radioList",
    options: ["Ni-Cd ", "VRLA"],
  },
  {
    id: "div",
    fieldName: "",
    fieldType: "divider",
  },
  {
    id: "date",
    fieldName: "Date",
    fieldType: "text",
    default: "#VAR_NOW#",
    enabled: false,
  },
  {
    id: "test",
    fieldName: "Tested By",
    fieldType: "text",
    default: "#VAR_UNAME#",
    enabled: false,
  },
  {
    id: "type",
    fieldName: "Test Type",
    fieldType: "radioList",
    options: ["M", "Q", "A"],
  },
  {
    id: "charg",
    fieldName: "Charger AC voltage",
    fieldType: "text",
  },
  {
    id: "c_curr",
    fieldName: "Battery Charge Current",
    fieldType: "text",
  },
  {
    id: "div1",
    fieldName: "",
    fieldType: "divider",
  },
  {
    id: "b_volt",
    fieldName: "Overall battery voltage",
    fieldType: "label",
  },
  {
    id: "c_on",
    fieldName: "Charger On",
    fieldType: "text",
  },
  {
    id: "c_off",
    fieldName: "Charger Off",
    fieldType: "text",
  },
  {
    id: "div2",
    fieldName: "",
    fieldType: "divider",
  },
  {
    id: "c_volt",
    fieldName: "Cell Discharge Voltage (End of test with charger off)",
    fieldType: "label",
  },
  {
    id: "row1",
    fieldName: "1",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "row2",
    fieldName: "2",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "row3",
    fieldName: "3",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "row4",
    fieldName: "4",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "row5",
    fieldName: "5",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "row6",
    fieldName: "6",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "row7",
    fieldName: "7",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "row8",
    fieldName: "8",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "row9",
    fieldName: "9",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "row10",
    fieldName: "10",
    fieldType: "number",
    numberDecimal: true,
  },
  {
    id: "div3",
    fieldName: "",
    fieldType: "divider",
  },
  {
    id: "g_volt",
    fieldName: "Battery Grounds Voltage",
    fieldType: "text",
  },
  {
    id: "adjust",
    fieldName: "Charger Adjusted?",
    fieldType: "radioList",
    options: ["Yes", "No"],
  },
  {
    id: "water",
    fieldName: "Water Added (inches)",
    fieldType: "text",
  },
  {
    id: "e_app",
    fieldName: "Equalizing Charges Applied (Reason, duration, results)",
    fieldType: "text",
  },
  {
    id: "rep",
    fieldName: "Repairs, Replacement, etc. (Provide details)",
    fieldType: "text",
  },
];
