export const mWpt = {
  _doc: {
    _id: "-1",
    runRanges: [],
    inspectionFrequencies: [],
    tasks: [
      {
        title: "Perform Maintenance",
        desc: "Perform Maintenance",
        notes: "Default Maintenance Notes",
        units: [
          {
            start: 0,
            end: 0,
            unitId: "Maintain",
            coordinates: [
              [0, 0],
              [0, 0],
            ],
            assetType: "Lines",
            id: "-1",
            runId: "Maintain",
            run_id: "-1",
            track_id: null,
            parent_id: "-1",
            attributes: {
              showDirection: false,
            },
          },
          {
            start: 0,
            end: 0,
            unitId: "Maintain",
            coordinates: [
              [0, 0],
              [0, 0],
            ],
            assetType: "track",
            id: "-1",
            runId: "Maintain",
            run_id: "-1",
            track_id: null,
            parent_id: "-1",
            attributes: {
              showDirection: false,
            },
          },
        ],
        imgs: null,
        taskId: "-1",
        startLoc: {
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: [-0, 0],
          },
        },
        endLoc: {
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: [-0, 0],
          },
        },
        lineCords: {
          id: "-1",
          runId: "-1",
          geometry: {
            type: "LineString",
            coordinates: [],
          },
        },
        runId: "Maintain",
        runStart: 0,
        runEnd: 0,
      },
    ],
    active: true,
    inspectionAssets: [],
    isRemoved: false,
    type: 0,
    sort_id: 0,
    title: "Maintainence Work",
    user: {
      _id: "-1",
      name: "",
      email: "",
    },
    startDate: "",
    inspectionType: "",
    FRAOption: "",
    inspectionFrequency: 0,
    maxAllowable: 0,
    lineId: "-1",
    inspectionRun: "",
    workZone: false,
    foulTime: false,
    watchmen: "",
    nextInspectionDate: "",
    createdAt: "",
    updatedAt: "",
    __v: 0,
    completion: {
      completed: false,
      ranges: [],
    },
    currentPeriodEnd: "",
    currentPeriodStart: "",
    nextDueDate: "",
    nextExpiryDate: "",
    perTime: "0",
    timeFrame: "",
  },
};
