export const onrDetailedMonthlyTurnoutForm = {
  code: "onrTurnoutForm",
  tenantId: "ps19",
  description: "ONR Detailed Mainline Turnout Inspection Form",
  listName: "appForms",
  opt1: [
    {
      id: "inspected",
      fieldName: "Scheduled Inspection",
      fieldType: "checkbox",
      tag: "completionCheck",
    },
    {
      id: "post",
      fieldName: "Switch Position",
      fieldType: "radioList",
      options: ["Right", "Left"],
    },
    {
      id: "samstnd",
      fieldName: "Samson/Standard",
      fieldType: "text",
    },
    {
      id: "toti",
      fieldName: "Type of Turnout",
      fieldType: "text",
    },
    {
      id: "rsize",
      fieldName: "Rail Size",
      fieldType: "text",
    },
    {
      id: "gl6",
      fieldName: "Gauge (5'-10' ahead of points)",
      fieldType: "text",
    },
    {
      id: "lcros10",
      fieldName: "Crosslevel (+/-) Main 1",
      fieldType: "text",
    },
    {
      id: "rcros10",
      fieldName: "Crosslevel (+/-) Turnout 1",
      fieldType: "text",
    },
    {
      id: "pe1",
      fieldName: "Point Elevation Main",
      fieldType: "text",
    },
    {
      id: "pe2",
      fieldName: "Point Elevation Turnout",
      fieldType: "text",
    },
    {
      id: "gah1",
      fieldName: "Gauge at heel Main",
      fieldType: "text",
    },
    {
      id: "gah2",
      fieldName: "Gauge at heel Turnout",
      fieldType: "text",
    },
    {
      id: "lcros9",
      fieldName: "Crosslevel (+/-) Main 2",
      fieldType: "text",
    },
    {
      id: "rcros9",
      fieldName: "Crosslevel (+/-) Turnout 2",
      fieldType: "text",
    },
    {
      id: "lcros8",
      fieldName: "Crosslevel (+/-) Main 3",
      fieldType: "text",
    },
    {
      id: "rcros8",
      fieldName: "Crosslevel (+/-) Turnout 3",
      fieldType: "text",
    },
    {
      id: "lcros7",
      fieldName: "Crosslevel (+/-) Main 4",
      fieldType: "text",
    },
    {
      id: "rcros7",
      fieldName: "Crosslevel (+/-) Turnout 4",
      fieldType: "text",
    },
    {
      id: "gl5",
      fieldName: "Gauge Main 1",
      fieldType: "text",
    },
    {
      id: "gr5",
      fieldName: "Gauge Turnout 1",
      fieldType: "text",
    },
    {
      id: "lcros6",
      fieldName: "Crosslevel (+/-) Main 5",
      fieldType: "text",
    },
    {
      id: "rcros6",
      fieldName: "Crosslevel (+/-) Turnout 5",
      fieldType: "text",
    },
    {
      id: "lcros5",
      fieldName: "Crosslevel (+/-) Main 6",
      fieldType: "text",
    },
    {
      id: "rcros5",
      fieldName: "Crosslevel (+/-) Turnout 6",
      fieldType: "text",
    },
    {
      id: "gl4",
      fieldName: "Gauge Main 2",
      fieldType: "text",
    },
    {
      id: "gr4",
      fieldName: "Gauge Turnout 2",
      fieldType: "text",
    },
    {
      id: "fd1",
      fieldName: "Flangeway Depth Main",
      fieldType: "text",
    },
    {
      id: "fd2",
      fieldName: "Flangeway Depth Turnout",
      fieldType: "text",
    },
    {
      id: "gf1",
      fieldName: "Guard Face Main",
      fieldType: "text",
    },
    {
      id: "gf2",
      fieldName: "Guard Face Turnout",
      fieldType: "text",
    },
    {
      id: "gc1",
      fieldName: "Guard Check Main",
      fieldType: "text",
    },
    {
      id: "gc2",
      fieldName: "Guard Check Turnout",
      fieldType: "text",
    },
    {
      id: "gl3",
      fieldName: "Gauge Main 3",
      fieldType: "text",
    },
    {
      id: "gr3",
      fieldName: "Gauge Turnout 3",
      fieldType: "text",
    },
    {
      id: "lcros4",
      fieldName: "Crosslevel (+/-) Main 7",
      fieldType: "text",
    },
    {
      id: "rcros4",
      fieldName: "Crosslevel (+/-) Turnout 7",
      fieldType: "text",
    },
    {
      id: "lcros3",
      fieldName: "Crosslevel (+/-) Main 8",
      fieldType: "text",
    },
    {
      id: "rcros3",
      fieldName: "Crosslevel (+/-) Turnout 8",
      fieldType: "text",
    },
    {
      id: "gl2",
      fieldName: "Gauge Main 4",
      fieldType: "text",
    },
    {
      id: "gr2",
      fieldName: "Gauge Turnout 4",
      fieldType: "text",
    },
    {
      id: "lcros2",
      fieldName: "Crosslevel (+/-) Main 9",
      fieldType: "text",
    },
    {
      id: "rcros2",
      fieldName: "Crosslevel (+/-) Turnout 9",
      fieldType: "text",
    },
    {
      id: "lcros1",
      fieldName: "Crosslevel (+/-) Main 10",
      fieldType: "text",
    },
    {
      id: "rcros1",
      fieldName: "Crosslevel (+/-) Turnout 10",
      fieldType: "text",
    },
    {
      id: "gl1",
      fieldName: "Gauge Main 5",
      fieldType: "text",
    },
    {
      id: "gr1",
      fieldName: "Gauge Turnout 5",
      fieldType: "text",
    },
    {
      id: "div",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "ballast",
      fieldName: "Ballast & Drainage",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div1",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "line",
      fieldName: "Line",
      fieldType: "label",
    },
    {
      id: "div2",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "main1",
      fieldName: "Main",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "side1",
      fieldName: "Siding",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div3",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "surf",
      fieldName: "Surface",
      fieldType: "label",
    },
    {
      id: "div4",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "main2",
      fieldName: "Main",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "side2",
      fieldName: "Siding",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div5",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "ties",
      fieldName: "Ties",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "plate",
      fieldName: "Plates",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "rail",
      fieldName: "Rails",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "pins",
      fieldName: "Cotter Pins",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "bolt",
      fieldName: "Bolts",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div6",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "braces",
      fieldName: "Rail Braces",
      fieldType: "label",
    },
    {
      id: "div7",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "type1",
      fieldName: "Type",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "cond1",
      fieldName: "Condition",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div8",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "ranchor",
      fieldName: "Rail Anchors",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div9",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "point",
      fieldName: "Points (fit)",
      fieldType: "label",
    },
    {
      id: "div10",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "left1",
      fieldName: "Left",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "right1",
      fieldName: "Right",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div11",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "runsurf",
      fieldName: "Points (running surface)",
      fieldType: "label",
    },
    {
      id: "div12",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "left2",
      fieldName: "Left",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "right2",
      fieldName: "Right",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div13",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "heelb",
      fieldName: "Heel Block",
      fieldType: "label",
    },
    {
      id: "div14",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "left3",
      fieldName: "Left",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "right3",
      fieldName: "Right",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div15",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "switchkep",
      fieldName: "Switch Locks/Keepers",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div16",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "stand1",
      fieldName: "Switch Stand",
      fieldType: "label",
    },
    {
      id: "div17",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "type2",
      fieldName: "Type",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "cond2",
      fieldName: "Condition",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "div18",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "starget",
      fieldName: "Switch Target",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "genfrog",
      fieldName: "Frog General",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "lubric",
      fieldName: "Lubrication",
      fieldType: "radioList",
      options: ["Good", "Fair", "Poor"],
    },
    {
      id: "com",
      fieldName: "Comments",
      fieldType: "text",
    },
    {
      id: "note",
      fieldName: "NOTE:  Crosslevel measurements must be taken at locations 15' 6'' apart on both routes throughout the turnout",
      fieldType: "label",
    },
    {
      id: "spa",
      fieldName: "",
      fieldType: "label",
    },
    {
      id: "note2",
      fieldName: "All Gauge and Crosslevel measurements should be taken starting at the switch point and moving out.",
      fieldType: "label",
    },
    {
      id: "sp",
      fieldName: "",
      fieldType: "label",
    },
  ],
  opt2: {
    config: [],
    allowedInstruction: [],
    restrictAssetTypes: [],
    allowedAssetTypes: ["Switch", "Turnout 2", "Turnout 3", "Turnout 4"],
  },
};
