export const frmMonthlySI4QNS = {
  tenantId: "ps19",
  listName: "appForms",
  code: "frmMonthlySI4QNS",
  description: "INSPECTION MENSUELLE DES AIGUILLAGES",
  opt2: {
    config: [],
    allowedInstruction: [],
    restrictAssetTypes: [],
    allowedAssetTypes: ["Switch"],
  },
  opt1: [
    {
      id: "inspected",
      fieldName: "Oui",
      fieldType: "checkbox",
      tag: "completionCheck",
    },
    {
      id: "chemin",
      fieldName: "CHEMIN DE FER QNS&L",
      fieldType: "label",
    },
    {
      id: "insptitle",
      fieldName: "INSPECTION MENSUELLE DES AIGUILLAGES",
      fieldType: "label",
    },
    {
      id: "endroit",
      fieldName: "ENDROIT:",
      fieldType: "text",
    },
    {
      id: "inspector",
      fieldName: "INSPECTEUR:",
      fieldType: "text",
      default: "#VAR_UNAME#",
      enabled: false,
    },
    {
      id: "verification",
      fieldName: "VÉRIFICATIONS",
      fieldType: "label",
    },
    {
      id: "coursedes",
      fieldName: "COURSE DES AIGUILLES LINÉARITÉ DE LA POINTE",
      fieldType: "label",
    },
    {
      id: "tolerances",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "rod11",
      fieldName: '1ÈRE ROD: 4 3/4" (±1/16")',
      fieldType: "label",
    },
    {
      id: "mesures1",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "vp1",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ve1",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "remarks1",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "tolerances2",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "rod22",
      fieldName: '2IÈME ROD: 3 15/16" (±1/16")',
      fieldType: "label",
    },
    {
      id: "mesures2",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "vp2",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ve2",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "remarks2",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "tolerances3",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "rod33",
      fieldName: '3IÈME ROD: 3 3/16"  (±1/16")',
      fieldType: "label",
    },
    {
      id: "mesures3",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "vp3",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ve3",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "remarks3",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "cotede",
      fieldName: "COTE DE PROTECTION DU CONTRE-RAIL / GUARD RAIL",
      fieldType: "label",
    },
    {
      id: "tolerances4",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "rod12",
      fieldName: '1 7/8" (± 1/8")',
      fieldType: "label",
    },
    {
      id: "mesures4",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "vp4",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ve4",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "remarks4",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "coteprotection",
      fieldName: "COTE DE PROTECTION POINTE DU CŒUR DE CROISEMENT",
      fieldType: "label",
    },
    {
      id: "tolerances5",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "rod12",
      fieldName: '54 5/8"  ( - 1/4" , + 0" )',
      fieldType: "label",
    },
    {
      id: "mesures5",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "vp5",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ve5",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "remarks5",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "div01",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "inspectionvisuelle",
      fieldName: "INSPECTION VISUELLE",
      fieldType: "label",
    },
    {
      id: "div02",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "selectiondspoints",
      fieldName: "SECTION DES POINTES",
      fieldType: "label",
    },
    {
      id: "pointecolle1",
      fieldName: "POINTE COLLE BIEN EN POSITION NORMALE",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis1",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description1",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "pointecolle2",
      fieldName: "POINTE COLLE BIEN EN POSITION RENVERSÉE",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis2",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description2",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "conditionpoint1",
      fieldName: "CONDITION DE LA POINTE C/O - C/S",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis3",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description3",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "conditionpoint2",
      fieldName: "CONDITION DE LA POINTE C/E - C/N",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis4",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description4",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "contrefiche1",
      fieldName: "CONTRE-FICHE C/O - C/S (BRACE-BLOCK)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis5",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description5",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "contrefiche2",
      fieldName: "CONTRE-FICHE C/E - C/N (BRACE-BLOCK)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis6",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description6",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "contrefiche2a",
      fieldName: "BOULONS DE CONTRE-FICHE C/O - C/S (BRACE-BLOCK BOLTS)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis6a",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description6a",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "contrefiche2b",
      fieldName: "BOULONS DE CONTRE-FICHE C/E - C/N (BRACE-BLOCK BOLTS)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis6b",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description6b",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "contreaiguille1",
      fieldName: "CONTRE-AIGUILLE C/O - C/S (STOCK-RAIL)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis7",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description7",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "contreaiguille2",
      fieldName: "CONTRE-AIGUILLE C/E - C/N (STOCK-RAIL)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis8",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description8",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "trianglerods",
      fieldName: "TRINGLES D'ÉCARTEMENT (RODS)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis9",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description9",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "boulonsdes1",
      fieldName: "BOULONS DES TRINGLES D'ÉCARTEMENT (RODS BOLTS)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis10",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description10",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "goupilles",
      fieldName: "GOUPILLES",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis11",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description11",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "sellesde1",
      fieldName: "SELLES DE GLISSEMENT (PLATES)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis12",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description12",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "conditiondes1",
      fieldName: "CONDITION DES DORMANTS (TIES)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis13",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description13",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "carmponset1",
      fieldName: "CRAMPONS ET SYSTÈME D'ATTACHE",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis14",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description14",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "nivellementet1",
      fieldName: "NIVELLEMENT ET ALIGNEMENT",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis15",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description15",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "div03",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "sectiondu1",
      fieldName: "SECTION DU CŒUR DE CROISSEMENT    CŒUR # :",
      fieldType: "text",
    },
    {
      id: "div04",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "ceurde2",
      fieldName: "CŒUR DE CROISSEMENT (FROG)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis16",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description16",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "boulonsdu2",
      fieldName: "BOULONS DU CŒUR DE CROISSEMENT",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis17",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description17",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "roues2",
      fieldName: "ROUES TOUCHES CÔTÉ POINTE",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis18",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description18",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "roues3",
      fieldName: "ROUES TOUCHES CÔTÉ AILES",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis19",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description19",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "sellesdu3",
      fieldName: "SELLES DU CŒUR DE CROISSEMENT (PLATES)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis20",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description20",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "crampons1",
      fieldName: "CRAMPONS, SYSTÈME D'ATTACHE",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis21",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description21",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "contrerail1",
      fieldName: "CONTRE-RAIL C/O - C/S (GUARD-RAIL)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis22",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description22",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "contrerail2",
      fieldName: "CONTRE-RAIL C/E - C/N (GUARD-RAIL)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis23",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description23",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "adjustercote1",
      fieldName: "AJUSTER COTE DE PROTECTION C/O - C/S",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis24",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description24",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "adjustercote2",
      fieldName: "AJUSTER COTE DE PROTECTION C/E - C/N",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis25",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description25",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "boulonsdu3",
      fieldName: "BOULONS DU CONTRE-RAIL C/O - C/S (GUARD-RAIL)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis26",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description26",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "boulonsdu4",
      fieldName: "BOULONS DU CONTRE-RAIL C/E - C/N (GUARD-RAIL)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis27",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description27",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "conditiondes2",
      fieldName: "CONDITION DES DORMANTS (TIES)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis28",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description28",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "nivellementet2",
      fieldName: "NIVELLEMENT ET ALIGNEMENT",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis29",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description29",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "div04",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "generalaspect",
      fieldName: "ASPECT GÉNÉRAL DE L'AIGUILLAGE",
      fieldType: "label",
    },
    {
      id: "div05",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "etatdu2",
      fieldName: "ÉTAT DU BALLAST ET DE L'ÉPAULEMENT",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis30",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description30",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "conditiondes3",
      fieldName: "CONDITION DES DORMANTS (TIES)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis31",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description31",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "div06",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "avantdes2",
      fieldName: "AVANT DES POINTES",
      fieldType: "label",
    },
    {
      id: "jointsisolves1",
      fieldName: "JOINTS ISOLÉS VP C/O - C/S",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis32",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description32",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "jointsisolves2",
      fieldName: "JOINTS ISOLÉS VP C/E - C/N",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis33",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description33",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "div07",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "avantcoeur1",
      fieldName: "AVANT COEUR DE CROISEMENT (FROG)",
      fieldType: "label",
    },
    {
      id: "jointsisolves3",
      fieldName: "JOINTS ISOLÉS VP C/O - C/S",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis34",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description34",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "jointsisolves4",
      fieldName: "JOINTS ISOLÉS VP C/E - C/N",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis35",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description35",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "div08",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "jointsisolves5",
      fieldName: "JOINTS ISOLÉS VE C/O - C/S",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis37",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description37",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "jointsisolves6",
      fieldName: "JOINTS ISOLÉS VE C/E - C/N",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis38",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description38",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "jointsisolves7",
      fieldName: "JOINTS ISOLÉS VP C/O - C/S",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis39",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description39",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "jointsisolves8",
      fieldName: "JOINTS ISOLÉS VP C/E - C/N",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis40",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description40",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "rail1",
      fieldName: "RAIL",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis41",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description41",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "rail2",
      fieldName: "RAIL",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis42",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description42",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "rail3",
      fieldName: "RAIL",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis43",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description43",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "rail4",
      fieldName: "RAIL",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis44",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description44",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "autres1",
      fieldName: "AUTRES COMPOSANTES",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis44a",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description44a",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "cadenaseten1",
      fieldName: "CADENAS VÉRROUILLÉ ET EN BON ÉTAT",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "avis45",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "description45",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "comments1",
      fieldName: "COMMENTAIRES:",
      fieldType: "text",
    },
    {
      id: "bm1",
      fieldName: "BM #",
      fieldType: "text",
    },
    {
      id: "codedubm",
      fieldName: "CODE DU BM :",
      fieldType: "text",
    },
    {
      id: "datedubm",
      fieldName: "DATE DU BM :",
      fieldType: "text",
    },
  ],
};
