export const frmAnnualSI4QNS = {
  tenantId: "ps19",
  listName: "appForms",
  code: "frmAnnualSI4QNS",
  description: "INSPECTION ANNUELLE DES AIGUILLAGES",
  opt2: {
    config: [],
    allowedInstruction: [],
    restrictAssetTypes: [],
    allowedAssetTypes: ["Switch"],
  },
  opt1: [
    {
      id: "inspected",
      fieldName: "Oui",
      fieldType: "checkbox",
      tag: "completionCheck",
    },
    {
      id: "achemin",
      fieldName: "CHEMIN DE FER QNS&L",
      fieldType: "label",
    },
    {
      id: "ainsptitle",
      fieldName: "INSPECTION ANNUELLE DES AIGUILLAGES",
      fieldType: "label",
    },
    {
      id: "aendroit",
      fieldName: "ENDROIT:",
      fieldType: "text",
    },
    {
      id: "ainspector",
      fieldName: "INSPECTEUR:",
      fieldType: "text",
      default: "#VAR_UNAME#",
      enabled: false,
    },
    {
      id: "averification",
      fieldName: "VÉRIFICATIONS",
      fieldType: "label",
    },
    {
      id: "acoursedes",
      fieldName: "COURSE DES AIGUILLES LINÉARITÉ DE LA POINTE",
      fieldType: "label",
    },
    {
      id: "atolerances",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "arod11",
      fieldName: '1ÈRE ROD: 4 3/4" (±1/16")',
      fieldType: "label",
    },
    {
      id: "amesures1",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "avp1",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ave1",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "aremarks1",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "atolerances2",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "arod22",
      fieldName: '2IÈME ROD: 3 15/16" (±1/16")',
      fieldType: "label",
    },
    {
      id: "amesures2",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "avp2",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ave2",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "aremarks2",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "atolerances3",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "arod33",
      fieldName: '3IÈME ROD: 3 3/16"  (±1/16")',
      fieldType: "label",
    },
    {
      id: "amesures3",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "avp3",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ave3",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "aremarks3",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "acotede",
      fieldName: "COTE DE PROTECTION DU CONTRE-RAIL / GUARD RAIL",
      fieldType: "label",
    },
    {
      id: "atolerances4",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "arod12",
      fieldName: '1 7/8" (± 1/8")',
      fieldType: "label",
    },
    {
      id: "amesures4",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "avp4",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ave4",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "aremarks4",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "acoteprotection",
      fieldName: "COTE DE PROTECTION POINTE DU CŒUR DE CROISEMENT",
      fieldType: "label",
    },
    {
      id: "atolerances5",
      fieldName: "TOLÉRANCES",
      fieldType: "label",
    },
    {
      id: "arod12",
      fieldName: '54 5/8"  ( - 1/4" , + 0" )',
      fieldType: "label",
    },
    {
      id: "amesures5",
      fieldName: "MESURES",
      fieldType: "label",
    },
    {
      id: "avp5",
      fieldName: "VP",
      fieldType: "text",
    },
    {
      id: "ave5",
      fieldName: "VE",
      fieldType: "text",
    },
    {
      id: "aremarks5",
      fieldName: "REMARQUES",
      fieldType: "text",
    },
    {
      id: "adiv01",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "ainspectionvisuelle",
      fieldName: "INSPECTION VISUELLE",
      fieldType: "label",
    },
    {
      id: "adiv02",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "aselectiondspoints",
      fieldName: "SECTION DES POINTES",
      fieldType: "label",
    },
    {
      id: "asurelevation1",
      fieldName: 'SURÉLÉVATION DE LA POINTE (1/4") C/E - C/N ',
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis1",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc1",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "asurelevation2",
      fieldName: 'SURÉLÉVATION DE LA POINTE (1/4") C/O - C/S ',
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis2",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc2",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "aboulons1",
      fieldName: "BOULONS TALON DE LA POINTE C/O - C/S (HEEL-BLOCK BOLTS)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis3",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc3",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "aboulons2",
      fieldName: "BOULONS TALON DE LA POINTE C/E - C/N (HEEL-BLOCK BOLTS)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis4",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc4",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "anivell1",
      fieldName: "NIVELLEMENT TALON DE LA POINTE C/O - C/S (HEEL-BLOCK)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis5",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc5",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "anivell2",
      fieldName: "NIVELLEMENT TALON DE LA POINTE C/E - C/N (HEEL-BLOCK)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis6",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc6",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "adiv03",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "aaspect1",
      fieldName: "ASPECT GÉNÉRAL DE L'AIGUILLAGE",
      fieldType: "label",
    },
    {
      id: "anivell3",
      fieldName: "NIVELLEMENT ET ALIGNEMENT (DONNÉES DU 454)",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis7",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc7",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "adiv04",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "aecartement1",
      fieldName: "ÉCARTEMENT DE LA VOIE",
      fieldType: "label",
    },
    {
      id: "apied1",
      fieldName: "5 À 10 PIEDS AVANT LES AIGUILLES",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis8",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc8",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "aentre1",
      fieldName: "V/E À L'ENTRETOISE DU TALON",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis9",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc9",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "amedpoint1",
      fieldName: "V/E AU POINT MÉDIAN DU RAIL INTERMÉDIAIRE",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis10",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc10",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "aapresde1",
      fieldName: "V/E APRÈS LE CŒUR DE CROISEMENT",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis11",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc11",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "apied2",
      fieldName: "V/E 20 PIEDS APRÈS LE CŒUR DE CROISEMENT",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis12",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc12",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "apied3",
      fieldName: "V/E 40 PIEDS APRÈS LE CŒUR DE CROISEMENT",
      fieldType: "radioList",
      options: ["BON ÉTAT", "AJUSTER", "REMPLACER"],
    },
    {
      id: "aavis13",
      fieldName: "AVIS",
      fieldType: "text",
    },
    {
      id: "adesc13",
      fieldName: "DESCRIPTION",
      fieldType: "text",
    },
    {
      id: "acomment1",
      fieldName: "COMMENTAIRES:",
      fieldType: "text",
    },
    {
      id: "abm1",
      fieldName: "BM #",
      fieldType: "text",
    },
    {
      id: "acodedubm",
      fieldName: "CODE DU BM :",
      fieldType: "text",
    },
    {
      id: "adatedubm",
      fieldName: "DATE DU BM :",
      fieldType: "text",
    },
  ],
};
