export const rolesPermissionUpdate = true;

export const permissionsToAdd = [
  { name: "USER VIEW", resource: "USER", action: "view" },
  { name: "USER READ", resource: "USER", action: "read" },
  { name: "USER CREATE", resource: "USER", action: "create" },
  { name: "USER UPDATE", resource: "USER", action: "update" },
  { name: "USER DELETE", resource: "USER", action: "delete" },
  { name: "USER GROUP UPDATE", resource: "USER", action: "group_update" },
  { name: "SETUP PAGE", resource: "SETUP", action: "view" },
  { name: "TRACK READ", resource: "TRACK", action: "read" },
  { name: "TRACK CREATE", resource: "TRACK", action: "create" },
  { name: "TRACK UPDATE", resource: "TRACK", action: "update" },
  { name: "TRACK DELETE", resource: "TRACK", action: "delete" },
  { name: "TRACK VIEW", resource: "TRACK", action: "view" },
  { name: "WORKPLAN READ", resource: "WORKPLAN", action: "read" },
  { name: "WORKPLAN CREATE", resource: "WORKPLAN", action: "create" },
  { name: "WORKPLAN UPDATE", resource: "WORKPLAN", action: "update" },
  { name: "WORKPLAN DELETE", resource: "WORKPLAN", action: "delete" },
  { name: "WORKPLAN VIEW", resource: "WORKPLAN", action: "view" },
  { name: "WORKPLAN SORTING", resource: "WORKPLAN", action: "plan_sort" },
  { name: "ASSETGROUP WORKPLAN CREATE", resource: "TRACK WORKPLAN", action: "create" },
  { name: "MAINTENANCE READ", resource: "MAINTENANCE", action: "read" },
  { name: "MAINTENANCE CREATE", resource: "MAINTENANCE", action: "create" },
  { name: "MAINTENANCE UPDATE", resource: "MAINTENANCE", action: "update" },
  { name: "MAINTENANCE DELETE", resource: "MAINTENANCE", action: "delete" },
  { name: "MAINTENANCE VIEW", resource: "MAINTENANCE", action: "view" },
  { name: "WORKORDER READ", resource: "WORKORDER", action: "read" },
  { name: "WORKORDER CREATE", resource: "WORKORDER", action: "create" },
  { name: "WORKORDER UPDATE", resource: "WORKORDER", action: "update" },
  { name: "WORKORDER DELETE", resource: "WORKORDER", action: "delete" },
  { name: "WORKORDER VIEW", resource: "WORKORDER", action: "view" },
  { name: "DASHBOARD VIEW", resource: "DASHBOARD", action: "view" },
  { name: "INSPECTION TEMP WORKER VIEW", resource: "INSPECTION TEMP WORKER", action: "view" },
  { name: "ISSUE VIEW", resource: "ISSUE", action: "view" },
  { name: "ISSUE MR CREATE", resource: "ISSUE MR", action: "create" },
  { name: "ISSUE CLOSE UPDATE", resource: "ISSUE CLOSE", action: "update" },
  { name: "ISSUE REASON UPDATE", resource: "ISSUE REASON", action: "update" },
  { name: "ISSUE REASON VIEW", resource: "ISSUE REASON", action: "view" },
  { name: "ISSUE MR VIEW", resource: "ISSUE MR", action: "view" },
  { name: "ISSUE UPDATE", resource: "ISSUE", action: "update" },
  { name: "MAINTENANCE DETAIL VIEW", resource: "MAINTENANCE DETAIL", action: "view" },
  { name: "MAINTENANCE WORK ORDER VIEW", resource: "MAINTENANCE WORK ORDER", action: "view" },
  { name: "MAINTENANCE ADD ESTIMATE CREATE", resource: "MAINTENANCE ADD ESTIMATE", action: "create" },
  { name: "MAINTENANCE CHANGE LOG VIEW", resource: "MAINTENANCE CHANGE LOG", action: "view" },
  { name: "MAINTENANCE ESTIMATE UPDATE", resource: "MAINTENANCE ESTIMATE", action: "update" },
  { name: "MAINTENANCE ESTIMATE DELETE", resource: "MAINTENANCE ESTIMATE", action: "delete" },
  { name: "WORKORDER GIS VIEW", resource: "WORKORDER GIS", action: "view" },
  { name: "WORKORDER EXECUTE UPDATE", resource: "WORKORDER EXECUTE", action: "update" },
  { name: "WORKORDER CLOSE UPDATE", resource: "WORKORDER CLOSE", action: "update" },
  { name: "ASSET CREATE", resource: "ASSET", action: "create" },
  { name: "ASSET DELETE", resource: "ASSET", action: "delete" },
  { name: "ASSET VIEW", resource: "ASSET", action: "view" },
  { name: "ASSET READ", resource: "ASSET", action: "read" },
  { name: "ASSET UPDATE", resource: "ASSET", action: "update" },
  { name: "TEAM CREATE", resource: "TEAM", action: "create" },
  { name: "TEAM VIEW", resource: "TEAM", action: "view" },
  { name: "TEAM DELETE", resource: "TEAM", action: "delete" },
  { name: "RUN CREATE", resource: "RUN", action: "create" },
  { name: "RUN VIEW", resource: "RUN", action: "view" },
  { name: "RUN DELETE", resource: "RUN", action: "delete" },
  { name: "RUN RANGE CREATE", resource: "RUN RANGE", action: "create" },
  { name: "INSPECTION TASK CREATE", resource: "INSPECTION TASK", action: "create" },
  { name: "INSPECTION TASK UPDATE", resource: "INSPECTION TASK", action: "update" },
  { name: "INSPECTION TASK DELETE", resource: "INSPECTION TASK", action: "delete" },
  { name: "COMPANY VIEW", resource: "COMPANY", action: "view" },
  { name: "SETUP LIST DATA CREATE", resource: "SETUP LIST DATA", action: "create" },
  { name: "APPLICATIONLOOKUPS_VIEW", resource: "APPLICATIONLOOKUP", action: "view" },
  { name: "LOCATION VIEW", resource: "LOCATION", action: "view" },
];

export const inspectorPermissions = [
  { name: "USER VIEW", resource: "USER", action: "view" },
  { name: "USER READ", resource: "USER", action: "read" },
  { name: "SETUP PAGE", resource: "SETUP", action: "view" },
  { name: "TRACK READ", resource: "TRACK", action: "read" },
  { name: "TRACK VIEW", resource: "TRACK", action: "view" },
  { name: "WORKPLAN READ", resource: "WORKPLAN", action: "read" },
  { name: "WORKPLAN VIEW", resource: "WORKPLAN", action: "view" },
  { name: "MAINTENANCE READ", resource: "MAINTENANCE", action: "read" },
  { name: "MAINTENANCE VIEW", resource: "MAINTENANCE", action: "view" },
  { name: "WORKORDER READ", resource: "WORKORDER", action: "read" },
  { name: "WORKORDER VIEW", resource: "WORKORDER", action: "view" },
  { name: "DASHBOARD VIEW", resource: "DASHBOARD", action: "view" },
  { name: "DASHBOARD VIEW", resource: "DASHBOARD", action: "view" },
  { name: "ISSUE VIEW", resource: "ISSUE", action: "view" },
  { name: "ISSUE REASON VIEW", resource: "ISSUE REASON", action: "view" },
  { name: "ISSUE MR VIEW", resource: "ISSUE MR", action: "view" },
  { name: "MAINTENANCE DETAIL VIEW", resource: "MAINTENANCE DETAIL", action: "view" },
  { name: "MAINTENANCE WORK ORDER VIEW", resource: "MAINTENANCE WORK ORDER", action: "view" },
  { name: "MAINTENANCE CHANGE LOG VIEW", resource: "MAINTENANCE CHANGE LOG", action: "view" },
  { name: "WORKORDER GIS VIEW", resource: "WORKORDER GIS", action: "view" },
  { name: "ASSET VIEW", resource: "ASSET", action: "view" },
  { name: "ASSET READ", resource: "ASSET", action: "read" },
  { name: "TEAM VIEW", resource: "TEAM", action: "view" },
  { name: "RUN VIEW", resource: "RUN", action: "view" },
  { name: "COMPANY VIEW", resource: "COMPANY", action: "view" },
];
