export const nopbDetailedMonthlyTurnoutForm = {
  code: "nopbSwitchForm",
  tenantId: "ps19",
  description: "Switch Inspection Form",
  listName: "appForms",
  opt2: {
    config: [],
    allowedInstruction: [],
    restrictAssetTypes: [],
    allowedAssetTypes: ["Switch", "Yard Switch"],
  },
  opt1: [
    {
      id: "Inspected",
      fieldName: "Inspected",
      fieldType: "checkbox",
      tag: "completionCheck",
    },
    {
      id: "rsize",
      fieldName: "RAIL SIZE",
      fieldType: "list",
      options: ["-", "90", "115", "132", "133", "136"],
    },
    {
      id: "frogno",
      fieldName: "FROG #",
      fieldType: "list",
      options: ["-", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16 "],
    },
    {
      id: "ftype",
      fieldName: "FROG TYPE",
      fieldType: "radioList",
      options: ["Self Guarded", "RBM"],
    },
    {
      id: "swptlen",
      fieldName: "SW PT LENGTH (Inches)",
      fieldType: "list",
      options: [
        "-",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
      ],
    },
    {
      id: "swpty",
      fieldName: "SW PT TYPE",
      fieldType: "radioList",
      options: ["Straight", "Samson"],
    },
    {
      id: "swsta",
      fieldName: "SW STAND TYPE",
      fieldType: "text",
    },
    {
      id: "swoper",
      fieldName: "SW OPERATOR",
      fieldType: "text",
    },
    {
      id: "toside",
      fieldName: "T.O. SIDE",
      fieldType: "radioList",
      options: ["Left", "Right"],
    },
    {
      id: "insult",
      fieldName: "INSULATED",
      fieldType: "radioList",
      options: ["Yes", "No"],
    },
    {
      id: "div11",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "item",
      fieldName: "ITEMS CHECKED",
      fieldType: "label",
    },
    {
      id: "div12",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "align",
      fieldName: "ALIGNMENT",
      fieldType: "radioList",
      options: ["Yes", "No"],
    },
    {
      id: "surf",
      fieldName: "SURFACE",
      fieldType: "radioList",
      options: ["Yes", "No"],
    },
    {
      id: "cross",
      fieldName: "CROSSLEVEL",
      fieldType: "radioList",
      options: ["Yes", "No"],
    },
    {
      id: "div",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "str",
      fieldName: "MAX GAGE STR.",
      fieldType: "label",
    },
    {
      id: "inch1",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch1",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "div1",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "clos",
      fieldName: "MAX GAGE CLOSURE",
      fieldType: "label",
    },
    {
      id: "inch2",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch2",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "div2",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "srh",
      fieldName: "SWITCH POINT RH",
      fieldType: "label",
    },
    {
      id: "inch3",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch3",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "div3",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "slh",
      fieldName: "SWITCH POINT LH",
      fieldType: "label",
    },
    {
      id: "inch4",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch4",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "div4",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "heel",
      fieldName: "HEEL BLOCK",
      fieldType: "label",
    },
    {
      id: "inch5",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch5",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "div5",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "railer",
      fieldName: "STOCK RAIL STR",
      fieldType: "label",
    },
    {
      id: "inch6",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch6",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "div6",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "bent",
      fieldName: "STOCK RAIL BENT",
      fieldType: "label",
    },
    {
      id: "inch7",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch7",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "div7",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "side",
      fieldName: "CLOSUE RAIL- T/O SIDE",
      fieldType: "label",
    },
    {
      id: "inch8",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch8",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "div8",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "frog",
      fieldName: "FROG",
      fieldType: "label",
    },
    {
      id: "pin",
      fieldName: "POINT",
      fieldType: "radioList",
      options: ["Yes", "No"],
    },
    {
      id: "bolt",
      fieldName: "BOLTS",
      fieldType: "radioList",
      options: ["Yes", "No"],
    },
    {
      id: "div9",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "guard",
      fieldName: "GUARD RAIL",
      fieldType: "label",
    },
    {
      id: "chstr",
      fieldName: "GUARD CHECK STR.",
      fieldType: "label",
    },
    {
      id: "inch9",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch9",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "chto",
      fieldName: "GUARD CHECK T/O",
      fieldType: "label",
    },
    {
      id: "inch10",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch10",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "faces",
      fieldName: "GUARD FACE STR.",
      fieldType: "label",
    },
    {
      id: "inch11",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch11",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "faceto",
      fieldName: "GUARD FACE T/O",
      fieldType: "label",
    },
    {
      id: "inch13",
      fieldName: "Inches",
      fieldType: "list",
      options: ["-", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
    },
    {
      id: "pinch13",
      fieldName: "1/16th Fractions",
      fieldType: "list",
      options: [
        "-",
        "1/16",
        "2/16",
        "3/16",
        "4/16",
        "5/16",
        "6/16",
        "7/16",
        "8/16",
        "9/16",
        "10/16",
        "11/16",
        "12/16",
        "13/16",
        "14/16",
        "15/16",
      ],
    },
    {
      id: "div10",
      fieldName: "",
      fieldType: "divider",
    },
    {
      id: "joint",
      fieldName: "INSULATED JOINTS",
      fieldType: "radioList",
      options: ["Yes", "No"],
    },
    {
      id: "spgard",
      fieldName: "SWITCH POINT GUARD",
      fieldType: "radioList",
      options: ["Yes", "No"],
    },
    {
      id: "otm",
      fieldName: "OTM (BRACES/PLATES/RODS)",
      fieldType: "text",
    },
    {
      id: "sstan",
      fieldName: "SWITCH STAND",
      fieldType: "text",
    },
    {
      id: "tcond",
      fieldName: "TIE CONDITION",
      fieldType: "text",
    },
    {
      id: "comm",
      fieldName: "COMMENTS",
      fieldType: "text",
    },
    {
      id: "sp",
      fieldName: "",
      fieldType: "label",
    },
  ],
};
