import {
  distributionDcodes,
  transmissionDcodes,
  ugroundfacPadmountSwitchgearDcodes,
  padmountTransformersDcodes,
  streetLightDcodes,
} from "../DefectCodes/EutilDefectCodes";
export const DistributionOverheadFac = {
  assetType: "Distribution Overhead Facilities",
  assetTypeClassify: "point",
  lampAttributes: [],
  timpsAttributes: { code: "0014", description: "Distribution" },
  defectCodes: null,
  inspectionInstructions: "",
  inspectionForms: null,
  plannable: false,
  inspectable: true,
  location: false,
  defectCodesObj: distributionDcodes,
  inspectionFormsObj: null,
  allowedAssetTypes: [],
};

export const Transmission = {
  assetType: "Transmission",
  assetTypeClassify: "point",
  lampAttributes: [],
  timpsAttributes: { code: "0014", description: "Transmission" },
  defectCodes: null,
  inspectionInstructions: "",
  inspectionForms: null,
  plannable: false,
  inspectable: true,
  location: false,
  defectCodesObj: transmissionDcodes,
  inspectionFormsObj: null,
  allowedAssetTypes: [],
};

export const UndergroundFacilitiesPadmountSwitchgear = {
  assetType: "Pad Mount Switchgear – Switch Modules  ",
  assetTypeClassify: "point",
  lampAttributes: [],
  timpsAttributes: { code: "0014", description: "Padmount Switchgear" },
  defectCodes: null,
  inspectionInstructions: "",
  inspectionForms: null,
  plannable: false,
  inspectable: true,
  location: false,
  defectCodesObj: ugroundfacPadmountSwitchgearDcodes,
  inspectionFormsObj: null,
  allowedAssetTypes: [],
};

export const PadmountTransformers = {
  assetType: "Padmount Transformers",
  assetTypeClassify: "point",
  lampAttributes: [],
  timpsAttributes: { code: "0014", description: "Padmount Transformers" },
  defectCodes: null,
  inspectionInstructions: "",
  inspectionForms: null,
  plannable: false,
  inspectable: true,
  location: false,
  defectCodesObj: padmountTransformersDcodes,
  inspectionFormsObj: null,
  allowedAssetTypes: [],
};

export const Streetlight = {
  assetType: "Streetlight",
  assetTypeClassify: "point",
  lampAttributes: [],
  timpsAttributes: { code: "0014", description: "Streetlight" },
  defectCodes: null,
  inspectionInstructions: "",
  inspectionForms: null,
  plannable: false,
  inspectable: true,
  location: false,
  defectCodesObj: streetLightDcodes,
  inspectionFormsObj: null,
  allowedAssetTypes: [],
};

export const UndergroundStructures = {
  assetType: "Underground Structures (Pedestals)",
  assetTypeClassify: "point",
  lampAttributes: [],
  timpsAttributes: { code: "0014", description: "Underground Structures (Pedestals)" },
  defectCodes: null,
  inspectionInstructions: "",
  inspectionForms: null,
  plannable: false,
  inspectable: true,
  location: false,
  defectCodesObj: streetLightDcodes,
  inspectionFormsObj: null,
  allowedAssetTypes: [],
};